"""initial_schema

Revision ID: bc74a0a2c586
Revises: 
Create Date: 2026-01-11 01:09:57.883826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc74a0a2c586'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('exercise_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_exercise_name')
    )
    op.create_index(op.f('ix_exercise_definitions_user_id'), 'exercise_definitions', ['user_id'], unique=False)
    op.create_table('splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_splits_user_id'), 'splits', ['user_id'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('split_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['split_id'], ['splits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_split_id'), 'templates', ['split_id'], unique=False)
    op.create_table('completed_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('session_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_completed_sessions_user_id'), 'completed_sessions', ['user_id'], unique=False)
    op.create_table('template_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('exercise_definition_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_definition_id'], ['exercise_definitions.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_exercises_exercise_definition_id'), 'template_exercises', ['exercise_definition_id'], unique=False)
    op.create_index(op.f('ix_template_exercises_template_id'), 'template_exercises', ['template_id'], unique=False)
    op.create_table('workout_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('session_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_drafts_user_id'), 'workout_drafts', ['user_id'], unique=True)
    op.create_table('completed_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_definition_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('epley_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_definition_id'], ['exercise_definitions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['completed_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_completed_sets_exercise_definition_id'), 'completed_sets', ['exercise_definition_id'], unique=False)
    op.create_index(op.f('ix_completed_sets_session_id'), 'completed_sets', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_completed_sets_session_id'), table_name='completed_sets')
    op.drop_index(op.f('ix_completed_sets_exercise_definition_id'), table_name='completed_sets')
    op.drop_table('completed_sets')
    op.drop_index(op.f('ix_workout_drafts_user_id'), table_name='workout_drafts')
    op.drop_table('workout_drafts')
    op.drop_index(op.f('ix_template_exercises_template_id'), table_name='template_exercises')
    op.drop_index(op.f('ix_template_exercises_exercise_definition_id'), table_name='template_exercises')
    op.drop_table('template_exercises')
    op.drop_index(op.f('ix_completed_sessions_user_id'), table_name='completed_sessions')
    op.drop_table('completed_sessions')
    op.drop_index(op.f('ix_templates_split_id'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_splits_user_id'), table_name='splits')
    op.drop_table('splits')
    op.drop_index(op.f('ix_exercise_definitions_user_id'), table_name='exercise_definitions')
    op.drop_table('exercise_definitions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
